# Generated by Django 4.0.2 on 2022-02-18 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_company_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('coordinateX', models.FloatField()),
                ('coordinateY', models.FloatField()),
                ('srid', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('buyer', 'buyer'), ('logist', 'logist')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightKG', models.FloatField()),
                ('expectingPriceTenge', models.FloatField()),
                ('expectingDeliveryDate', models.DateTimeField()),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('OrderEvent', 'OrderEvent'), ('OrderCancelEvent', 'OrderCancelEvent'), ('OrderFreightReceiveEvent', 'OrderFreightReceiveEvent'), ('OrderFulfillmentEvent', 'OrderFulfillmentEvent'), ('OrderFailEvent', 'OrderFailEvent')], max_length=255)),
                ('FromLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_location_order', to='admin_analytics_service.location')),
                ('ToLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_location_order', to='admin_analytics_service.location')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offeredPriceTenge', models.FloatField()),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('OfferEvent', 'OfferEvent'), ('OfferAcceptEvent', 'OfferAcceptEvent')], max_length=255)),
                ('delivery_Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_analytics_service.delivery_company')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='admin_analytics_service.order')),
            ],
        ),
    ]
