# Generated by Django 4.0.2 on 2022-02-18 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_analytics_service', '0002_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='FromLocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_location_order', to='admin_analytics_service.location'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ToLocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_location_order', to='admin_analytics_service.location'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='expectingDeliveryDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='expectingPriceTenge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, choices=[('OrderEvent', 'OrderEvent'), ('OrderCancelEvent', 'OrderCancelEvent'), ('OrderFreightReceiveEvent', 'OrderFreightReceiveEvent'), ('OrderFulfillmentEvent', 'OrderFulfillmentEvent'), ('OrderFailEvent', 'OrderFailEvent')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='weightKG',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
