# Generated by Django 4.0.2 on 2022-02-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_analytics_service', '0003_alter_order_fromlocation_alter_order_tolocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
