# Generated by Django 4.0.2 on 2022-02-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_analytics_service', '0004_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fail_reason',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
