# Generated by Django 4.0.2 on 2022-02-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_analytics_service', '0007_userprofile_delivery_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_company',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery_company',
            name='delivery_company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery_company',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
